<?php include_once('whoVisited.php'); ?>

<!DOCTYPE html>
<html>

<head>

    <title>Request New User - Health</title>

    <link rel="stylesheet" type="text/css" href="view.css">

    <link href="https://fonts.googleapis.com/css?family=Rancho" rel="stylesheet">

    <link rel="icon" type="image/gif/png" href="LogoFonts.png">

    <script type="text/javascript" src="view.js"></script>

</head>

<body>

    <a href="../informed.php"><img id="top" src="LogoFonts.png" alt=""></a>
    <div id="form_container">

        <h1><a>Untitled Form</a></h1>
        <form id="form_32517" class="appnitro" method="post" action="insertActHealth.php">
            <div class="form_description">
                <h2>Request New User</h2>
                <p></p>
            </div>
            <ul>

                <li id="li_1">
                    <label class="description" for="element_1">Name </label>
                    <span>
			<input id="element_1_1" name= "firstnameHealth" class="element text" maxlength="255" size="30" value=""/>
			<label>First</label>
		</span>
                    <span>
			<input id="element_1_2" name= "lastnameHealth" class="element text" maxlength="255" size="30" value=""/>
			<label>Last</label>
		</span>
                </li>
                <li id="li_2">
                    <label class="description" for="element_2">Professional ID </label>
                    <div>
                        <input id="element_2" name="IDHealth" class="element text medium" type="text" maxlength="255" value="" />
                    </div>
                </li>
                <li id="li_2">
                    <label class="description" for="element_2">Email </label>
                    <div>
                        <input id="element_2" name="emailHealth" class="element text medium" type="text" maxlength="255" value="" />
                    </div>
                </li>
                <li id="li_5">
                    <label class="description" for="element_5">Sector </label>
                    <div>
                        <select class="element select medium" id="element_5" name="sectorHealth"> 
			<option value="" selected="selected"></option>
            <option value="Health Practitioner" >Health Practitioner</option>
        

		</select>
                    </div>
                </li>
                <li id="li_3">
                    <label class="description" for="element_3">Location </label>
                    <div>
                        <input id="element_3" name="locationHealth" class="element text medium" type="text" maxlength="255" value="" />
                    </div>
                </li>
                <li id="li_4">
                    <label class="description" for="element_4">Password </label>
                    <div>
                        <input id="element_4" name="passwordHealth" class="element text medium" type="password" maxlength="255" value="" />
                    </div>
                </li>

                <li class="buttons">
                    <input type="hidden" name="form_id" value="32517" />

                    <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                </li>
            </ul>

            <br/>

            <a href="../List_Forms_Health.php">Return to List of Forms</a>

        </form>
        <!--<div id="footer">
            Generated by <a href="http://www.phpform.org">pForm</a>
        </div>-->
    </div>
    <img id="bottom" src="bottom.png" alt="">
</body>

</html>