<?php include_once('whoVisited.php'); ?>

<!DOCTYPE html>
<html>

<head>

    <title>Narcotic Laws</title>

    <link rel="stylesheet" type="text/css" href="view.css">

    <link href="https://fonts.googleapis.com/css?family=Rancho" rel="stylesheet">

    <link rel="icon" type="image/gif/png" href="LogoFonts.png">

    <script type="text/javascript" src="view.js"></script>

</head>

<body id="main_body">

    <a href="../informed.php"><img id="top" src="LogoFonts.png" alt=""></a>
    <div id="form_container">

        <h1><a>Untitled Form</a></h1>
        <form id="form_32517" class="appnitro" method="post" action="insertLaw.php">
            <div class="form_description">
                <h2>Narcotic Laws</h2>
                <p></p>
            </div>
            <ul>
                <li>
                    <label class="description" for="typeDrug">Type of Drug Law </label>
                    <select class="element select medium" id="element_5" name="typeOfLaw"> 
			<option value="" selected="selected"></option>
        
            <option value="Soft Drug Law" >Soft Drug Law</option>
            <option value="Hard Drug Law" >Hard Drug Law</option>
		</select>
                </li>
                
                <li id="li_3">
                    <label class="description" for="element_3">Offense </label>
                    <div>
                        <input id="element_3" name="offense" class="element text medium" type="text" placeholder="Example: Possession < 0.5 g or < 1 user unit" />
                    </div>
                </li>
                <li id="li_3">
                    <label class="description" for="element_3">Sanction to be Sought </label>
                    <div>
                        <input id="element_3" name="sanction" class="element text medium" type="text" placeholder="Example: 1 week - 2 months" />
                    </div>
                </li>
               

                <li class="buttons">
                    <input type="hidden" name="form_id" value="32517" />

                    <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                </li>
            </ul>

            <br/>

            <a href="../List_Forms_Policy.php">Return to List of Forms</a>

        </form>
        <!--<div id="footer">
            Generated by <a href="http://www.phpform.org">pForm</a>
        </div>-->
    </div>
    <img id="bottom" src="bottom.png" alt="">
</body>

</html>